In [1]:
import numpy as np
import pandas as pd


tfidf_lr = pd.read_csv('prob_lr_baseline.csv') # PL score 0.9829
testcnn = pd.read_csv('prob_textcnn_test.csv') # 0.9811

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [3]:
tfidf_lr.head()

,class_prob_1,class_prob_2,class_prob_3,class_prob_4,class_prob_5,class_prob_6,class_prob_7,class_prob_8,class_prob_9,class_prob_10,class_prob_11,class_prob_12,class_prob_13,class_prob_14,class_prob_15,class_prob_16,class_prob_17,class_prob_18,class_prob_19,id
0,0.009596,0.005085,0.003575,0.012177,0.868415,0.005473,0.008542,0.003589,0.009099,0.003174,0.007488,0.005358,0.006223,0.020577,0.011534,0.001628,0.005055,0.003478,0.009935,0
1,0.027511,0.003511,0.012730,0.807908,0.003767,0.011680,0.007150,0.002700,0.006755,0.005030,0.002945,0.034033,0.003694,0.006506,0.006110,0.003111,0.002039,0.047396,0.005425,1
2,0.033142,0.012992,0.086803,0.006567,0.018099,0.003494,0.019700,0.158008,0.005527,0.006570,0.025015,0.037754,0.503280,0.005185,0.024440,0.000099,0.020258,0.007865,0.025202,2
3,0.003471,0.001596,0.008642,0.922218,0.002760,0.025507,0.002346,0.004732,0.002355,0.001569,0.003865,0.005073,0.002084,0.002910,0.003320,0.000843,0.002231,0.002173,0.002305,3
4,0.062432,0.001765,0.004507,0.004155,0.723894,0.004958,0.036884,0.009596,0.015046,0.017516,0.025758,0.004690,0.016619,0.023731,0.013629,0.000456,0.004170,0.002491,0.027706,4

In [4]:
testcnn.head()

,class_prob_1,class_prob_2,class_prob_3,class_prob_4,class_prob_5,class_prob_6,class_prob_7,class_prob_8,class_prob_9,class_prob_10,class_prob_11,class_prob_12,class_prob_13,class_prob_14,class_prob_15,class_prob_16,class_prob_17,class_prob_18,class_prob_19,id
0,4.581186e-14,2.533037e-18,1.996236e-26,4.038745e-17,1.000000e+00,1.899932e-17,7.660647e-19,2.381735e-21,1.436659e-22,7.805838e-20,1.983701e-20,1.050623e-19,3.661243e-21,2.893169e-20,3.156373e-19,1.822734e-23,3.670277e-21,1.732062e-23,7.165433e-23,0
1,8.181404e-07,3.188546e-07,5.012753e-05,9.940646e-01,2.861792e-05,1.100280e-06,7.884467e-05,1.148067e-05,3.269993e-07,6.721647e-04,2.310360e-05,7.170939e-05,6.448972e-06,8.940686e-04,5.931897e-05,4.051524e-08,1.053403e-05,3.613417e-03,4.129732e-04,1
2,5.515654e-02,8.601285e-03,1.059846e-01,1.839746e-02,6.366640e-03,1.640298e-02,9.176292e-03,4.101149e-02,6.172595e-03,3.966669e-01,4.859974e-02,7.125797e-02,1.031309e-01,2.043002e-02,1.731283e-02,9.337640e-04,2.507469e-02,8.372606e-03,4.095060e-02,2
3,1.737144e-22,2.204048e-20,6.997608e-22,1.000000e+00,1.358356e-21,4.326718e-15,6.575565e-25,1.253348e-31,1.015116e-31,1.668750e-20,3.130060e-30,2.437565e-21,6.872854e-27,4.969401e-20,1.857726e-25,1.725487e-23,4.674859e-21,2.139034e-28,7.129864e-27,3
4,7.058860e-02,6.622186e-06,1.267986e-05,4.251748e-04,8.929684e-03,1.993545e-04,5.605798e-02,7.949879e-03,5.986725e-01,6.417050e-05,5.776855e-02,1.420059e-07,6.435970e-03,3.492688e-03,8.047064e-05,3.768092e-11,1.361177e-04,2.789619e-05,1.891515e-01,4

In [16]:
ensemble = tfidf_lr+testcnn

In [17]:
ensemble.head()

,class_prob_1,class_prob_2,class_prob_3,class_prob_4,class_prob_5,class_prob_6,class_prob_7,class_prob_8,class_prob_9,class_prob_10,class_prob_11,class_prob_12,class_prob_13,class_prob_14,class_prob_15,class_prob_16,class_prob_17,class_prob_18,class_prob_19,id
0,0.009596,0.005085,0.003575,0.012177,1.868415,0.005473,0.008542,0.003589,0.009099,0.003174,0.007488,0.005358,0.006223,0.020577,0.011534,0.001628,0.005055,0.003478,0.009935,0
1,0.027512,0.003512,0.012781,1.801973,0.003796,0.011681,0.007229,0.002711,0.006755,0.005702,0.002968,0.034105,0.003701,0.007400,0.006169,0.003111,0.002049,0.051009,0.005837,2
2,0.088299,0.021594,0.192788,0.024964,0.024466,0.019896,0.028876,0.199020,0.011700,0.403236,0.073615,0.109012,0.606411,0.025615,0.041753,0.001033,0.045332,0.016238,0.066153,4
3,0.003471,0.001596,0.008642,1.922218,0.002760,0.025507,0.002346,0.004732,0.002355,0.001569,0.003865,0.005073,0.002084,0.002910,0.003320,0.000843,0.002231,0.002173,0.002305,6
4,0.133020,0.001771,0.004520,0.004580,0.732823,0.005157,0.092942,0.017546,0.613719,0.017580,0.083526,0.004690,0.023055,0.027224,0.013709,0.000456,0.004306,0.002519,0.216857,8

In [18]:
ensemble = np.array(ensemble.drop(['id'],axis=1))

In [19]:
ensemble[:5]

array([[9.59620171e-03, 5.08457790e-03, 3.57473890e-03, 1.21771642e-02,
        1.86841465e+00, 5.47256350e-03, 8.54222744e-03, 3.58889335e-03,
        9.09853377e-03, 3.17351084e-03, 7.48781153e-03, 5.35787412e-03,
        6.22318831e-03, 2.05774715e-02, 1.15344239e-02, 1.62818757e-03,
        5.05500510e-03, 3.47784550e-03, 9.93513263e-03],
       [2.75115939e-02, 3.51151798e-03, 1.27806256e-02, 1.80197296e+00,
        3.79556229e-03, 1.16812675e-02, 7.22870781e-03, 2.71120530e-03,
        6.75483322e-03, 5.70221662e-03, 2.96803593e-03, 3.41051031e-02,
        3.70077914e-03, 7.39995694e-03, 6.16904234e-03, 3.11058042e-03,
        2.04920459e-03, 5.10093394e-02, 5.83748197e-03],
       [8.82989507e-02, 2.15936331e-02, 1.92787598e-01, 2.49641277e-02,
        2.44658775e-02, 1.98964807e-02, 2.88758543e-02, 1.99019693e-01,
        1.16999097e-02, 4.03236498e-01, 7.36147796e-02, 1.09012033e-01,
        6.06410874e-01, 2.56152663e-02, 4.17525130e-02, 1.03316284e-03,
        4.53322420e-02, 1.62377855e-02, 6.61526870e-02],
       [3.47059103e-03, 1.59634085e-03, 8.64203073e-03, 1.92221789e+00,
        2.75963827e-03, 2.55072769e-02, 2.34599585e-03, 4.73188374e-03,
        2.35526807e-03, 1.56876390e-03, 3.86472183e-03, 5.07324287e-03,
        2.08412556e-03, 2.91041723e-03, 3.32019408e-03, 8.42749930e-04,
        2.23076145e-03, 2.17280091e-03, 2.30530501e-03],
       [1.33020283e-01, 1.77138750e-03, 4.51987291e-03, 4.57998613e-03,
        7.32823203e-01, 5.15698325e-03, 9.29418074e-02, 1.75459558e-02,
        6.13718510e-01, 1.75797661e-02, 8.35263229e-02, 4.69023529e-03,
        2.30548492e-02, 2.72238859e-02, 1.37089772e-02, 4.55545526e-04,
        4.30649548e-03, 2.51875575e-03, 2.16857172e-01]])

In [30]:
all_predictions=np.argmax(ensemble,axis=1)

In [36]:
all_predictions = all_predictions+1

In [37]:
all_predictions[:5]

array([ 5,  4, 13,  4,  5])

In [32]:
test_id = pd.read_csv("data/test_set.csv")

In [38]:
test_pred=pd.DataFrame(all_predictions)
test_pred.columns=["class"]
test_pred["class"]=(test_pred["class"]).astype(int)
print(test_pred.shape)
print(test_id.shape)
test_pred["id"]=list(test_id["id"])
test_pred[["id","class"]].to_csv('ensemble.csv',index=None)

(102277, 1)
(102277, 3)

In [39]:
test_pred[:5]

   class  id
0      5   0
1      4   1
2     13   2
3      4   3
4      5   4