In [44]:
import numpy as np
import pandas as pd


tfidf_lr = pd.read_csv('result/prob/prob_lr_baseline.csv') # PL score 0.9829
svm_baseline = pd.read_csv('result/prob/prob_svm_baseline.csv') # 0.9811
svm_char_ngram13 = pd.read_csv('result/prob/prob_svm_char_ngram13.csv') # 0.9811
svm_word_ngram12 = pd.read_csv('result/prob/prob_svm_word_ngram12.csv')
lr_char_ngram13 = pd.read_csv('result/prob/prob_lr_char_ngram13.csv')
lr_word_ngram12 = pd.read_csv('result/prob/prob_lr_baseline.csv')
enhance_lr_word_ngram12 = pd.read_csv('result/prob/prob_enhance_lr_baseline.csv')
bigru_split = pd.read_csv('result/prob/prob_bigru_split.csv') # 0.74
bigru_split = bigru_split.groupby(bigru_split['id']).mean()
long_textcnn = pd.read_csv('result/prob/prob_long_textcnn_test.csv') # 0.73
mlp = pd.read_csv('result/prob/prob_mlp_top1000.csv') # 0.73
#mlp = pd.read_csv('result/prob/prob_long_textcnn_test.csv') # 0.73

In [47]:
textcnn_char = pd.read_csv('result/prob/prob_textcnn_char.csv')
textcnn_char = textcnn_char.drop(['id'],axis = 1)

In [35]:
nb = pd.read_csv('result/prob/prob_nb_baseline.csv')
nb = nb.drop(['id'],axis = 1)

In [1]:
bigru_split = pd.read_csv('result/prob/prob_bigru_split.csv') # 0.74
bigru_split = bigru_split.groupby(bigru_split['id']).mean()

NameError: name 'pd' is not defined

In [3]:
bigru_split.head()

,class_prob_1,class_prob_2,class_prob_3,class_prob_4,class_prob_5,class_prob_6,class_prob_7,class_prob_8,class_prob_9,class_prob_10,class_prob_11,class_prob_12,class_prob_13,class_prob_14,class_prob_15,class_prob_16,class_prob_17,class_prob_18,class_prob_19
id,,,,,,,,,,,,,,,,,,,
0,0.009295,1.204781e-03,1.776744e-04,0.000150,9.800779e-01,0.000292,0.001033,0.000199,2.833322e-07,3.468543e-03,0.000077,0.003260,3.985692e-05,0.000105,0.000136,1.433806e-04,0.000037,2.606056e-04,4.202165e-05
1,0.005287,3.073233e-06,1.767784e-06,0.983985,3.448950e-05,0.000179,0.000272,0.002595,3.787335e-05,4.223678e-04,0.000077,0.000720,1.213345e-04,0.004980,0.000152,4.368255e-05,0.000608,2.206046e-04,2.597412e-04
2,0.022193,4.719931e-02,2.193699e-02,0.000235,1.397110e-03,0.001215,0.000983,0.091145,3.039799e-04,7.732936e-02,0.011565,0.017006,6.286509e-01,0.001686,0.005917,4.225731e-04,0.000941,7.160808e-04,6.915723e-02
3,0.000058,5.602849e-10,3.839689e-10,0.999857,2.698765e-08,0.000004,0.000005,0.000019,3.158696e-07,3.480805e-07,0.000003,0.000002,1.920634e-07,0.000040,0.000002,3.532913e-09,0.000007,8.997761e-08,4.380488e-07
4,0.118646,7.650657e-04,5.667138e-04,0.002930,7.854701e-01,0.002408,0.007981,0.003926,4.159140e-05,1.911178e-02,0.026906,0.008911,4.844168e-03,0.003550,0.010554,4.069775e-05,0.001140,1.318175e-03,8.885068e-04

In [42]:
bigru_split.head()

,class_prob_1,class_prob_2,class_prob_3,class_prob_4,class_prob_5,class_prob_6,class_prob_7,class_prob_8,class_prob_9,class_prob_10,class_prob_11,class_prob_12,class_prob_13,class_prob_14,class_prob_15,class_prob_16,class_prob_17,class_prob_18,class_prob_19
id,,,,,,,,,,,,,,,,,,,
0,0.009295,1.204781e-03,1.776744e-04,0.000150,9.800779e-01,0.000292,0.001033,0.000199,2.833322e-07,3.468543e-03,0.000077,0.003260,3.985692e-05,0.000105,0.000136,1.433806e-04,0.000037,2.606056e-04,4.202165e-05
1,0.005287,3.073233e-06,1.767784e-06,0.983985,3.448950e-05,0.000179,0.000272,0.002595,3.787335e-05,4.223678e-04,0.000077,0.000720,1.213345e-04,0.004980,0.000152,4.368255e-05,0.000608,2.206046e-04,2.597412e-04
2,0.022193,4.719931e-02,2.193699e-02,0.000235,1.397110e-03,0.001215,0.000983,0.091145,3.039799e-04,7.732936e-02,0.011565,0.017006,6.286509e-01,0.001686,0.005917,4.225731e-04,0.000941,7.160808e-04,6.915723e-02
3,0.000058,5.602849e-10,3.839689e-10,0.999857,2.698765e-08,0.000004,0.000005,0.000019,3.158696e-07,3.480805e-07,0.000003,0.000002,1.920634e-07,0.000040,0.000002,3.532913e-09,0.000007,8.997761e-08,4.380488e-07
4,0.118646,7.650657e-04,5.667138e-04,0.002930,7.854701e-01,0.002408,0.007981,0.003926,4.159140e-05,1.911178e-02,0.026906,0.008911,4.844168e-03,0.003550,0.010554,4.069775e-05,0.001140,1.318175e-03,8.885068e-04

In [45]:
long_textcnn = long_textcnn.drop(['id'],axis = 1)

In [46]:
svm_char_ngram13 = svm_char_ngram13.drop(['id'],axis = 1)
svm_word_ngram12 = svm_word_ngram12.drop(['id'],axis = 1)
lr_char_ngram13 = lr_char_ngram13.drop(['id'],axis = 1)
lr_word_ngram12 = lr_word_ngram12.drop(['id'],axis = 1)
enhance_lr_word_ngram12 = enhance_lr_word_ngram12.drop(['id'],axis = 1)
mlp = mlp.drop(['id'],axis = 1)

In [90]:
ensemble = bigru_split + long_textcnn + svm_char_ngram13 + svm_word_ngram12 + lr_char_ngram13 + enhance_lr_word_ngram12 + textcnn_char + mlp

In [26]:
#ensemble = svm_char_ngram13 + svm_word_ngram12 + lr_char_ngram13 + lr_word_ngram12 + nb

In [91]:
ensemble.head()

,class_prob_1,class_prob_2,class_prob_3,class_prob_4,class_prob_5,class_prob_6,class_prob_7,class_prob_8,class_prob_9,class_prob_10,class_prob_11,class_prob_12,class_prob_13,class_prob_14,class_prob_15,class_prob_16,class_prob_17,class_prob_18,class_prob_19
id,,,,,,,,,,,,,,,,,,,
0,0.427428,0.069048,0.021379,0.068773,6.162765,0.051053,0.033066,0.056220,0.041429,0.054475,0.061355,0.037913,0.037541,0.335887,0.081183,0.366768,0.021850,0.019827,0.052038
1,0.167387,0.028056,0.669175,5.429508,0.026169,0.292052,0.042402,0.052817,0.028276,0.058401,0.031947,0.439744,0.040901,0.094581,0.119592,0.040595,0.024044,0.284813,0.129540
2,0.278433,0.118346,0.500127,0.071295,0.098947,0.037242,0.138394,0.821636,0.041050,0.156228,0.162580,0.421507,3.499862,0.976790,0.147275,0.041042,0.123261,0.052771,0.313213
3,0.040351,0.008704,0.035225,6.603267,0.012457,0.103462,0.012544,0.032746,0.012717,0.019969,0.022178,0.021339,0.235889,0.763443,0.011575,0.009376,0.014635,0.013572,0.026551
4,0.451345,0.025238,0.041995,0.435259,3.430273,0.030690,0.312036,0.068104,0.341708,0.251482,0.243460,0.739076,0.246979,0.375103,0.504040,0.011109,0.041266,0.008929,0.441908

In [92]:
# ensemble = split_textcnn.groupby(split_textcnn['id']).mean()

ensemble = np.array(ensemble)

In [53]:
ensemble = np.array(ensemble.drop(['id'],axis=1))

AttributeError: 'numpy.ndarray' object has no attribute 'drop'

In [93]:
ensemble[:5]

array([[0.42742786, 0.06904796, 0.02137931, 0.06877324, 6.16276476,
        0.05105339, 0.03306643, 0.05622025, 0.04142904, 0.05447511,
        0.06135531, 0.03791283, 0.0375413 , 0.33588746, 0.08118306,
        0.36676785, 0.02184993, 0.01982666, 0.05203829],
       [0.16738725, 0.02805565, 0.6691745 , 5.42950812, 0.02616874,
        0.29205183, 0.04240157, 0.05281746, 0.02827581, 0.05840137,
        0.03194674, 0.43974434, 0.04090083, 0.09458074, 0.11959249,
        0.04059538, 0.02404438, 0.28481337, 0.12953954],
       [0.27843345, 0.11834616, 0.50012679, 0.07129492, 0.09894706,
        0.0372423 , 0.13839447, 0.82163592, 0.04105046, 0.15622754,
        0.16257951, 0.42150666, 3.49986248, 0.97679   , 0.14727475,
        0.04104165, 0.12326147, 0.05277102, 0.31321328],
       [0.04035062, 0.00870436, 0.035225  , 6.60326731, 0.01245696,
        0.10346194, 0.01254413, 0.03274606, 0.01271703, 0.01996869,
        0.02217827, 0.02133853, 0.23588902, 0.76344297, 0.011575  ,
        0.00937612, 0.01463481, 0.01357237, 0.02655085],
       [0.45134496, 0.02523828, 0.04199513, 0.43525857, 3.43027272,
        0.03069037, 0.3120355 , 0.06810391, 0.34170769, 0.25148223,
        0.24346047, 0.73907581, 0.24697912, 0.37510294, 0.50403982,
        0.01110944, 0.04126555, 0.00892942, 0.44190816]])

In [94]:
all_predictions=np.argmax(ensemble,axis=1)

In [95]:
all_predictions = all_predictions+1

In [96]:
all_predictions[:5]

array([ 5,  4, 13,  4,  5])

In [78]:
test_id = pd.read_csv("data/test_set.csv")

In [99]:
test_pred=pd.DataFrame(all_predictions)
test_pred.columns=["class"]
test_pred["class"]=(test_pred["class"]).astype(int)
print(test_pred.shape)
print(test_id.shape)
test_pred["id"]=list(test_id["id"])
test_pred[["id","class"]].to_csv('submit/en_svm_enhancelr_spplitbigru_longtextcnn+textcnnchar+mlp.csv',index=None)

(102277, 1)
(102277, 3)

In [98]:
test_pred[:5]

   class  id
0      5   0
1      4   1
2     13   2
3      4   3
4      5   4